-- MySQL Script generated by MySQL Workbench
-- 10/23/15 20:37:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Floreria
-- -----------------------------------------------------
-- Modelo de la base de datos de Floreria(Proyecto de Administracion UV
-- )

-- -----------------------------------------------------
-- Schema Floreria
--
-- Modelo de la base de datos de Floreria(Proyecto de Administracion UV
-- )
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Floreria` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Floreria` ;

-- -----------------------------------------------------
-- Table `Floreria`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Floreria`.`reporte` (
  `idreporte` INT NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`idreporte`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Floreria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Floreria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombresCliente` VARCHAR(45) NOT NULL COMMENT '',
  `apellidosCliente` VARCHAR(45) NOT NULL COMMENT '',
  `direccionCliente` VARCHAR(45) NOT NULL COMMENT '',
  `telefonoCelular` VARCHAR(45) NULL COMMENT '',
  `telefonoCasa` VARCHAR(45) NULL COMMENT '',
  `reporte_idreporte` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcliente`)  COMMENT '',
  INDEX `fk_cliente_reporte1_idx` (`reporte_idreporte` ASC)  COMMENT '',
  CONSTRAINT `fk_cliente_reporte1`
    FOREIGN KEY (`reporte_idreporte`)
    REFERENCES `Floreria`.`reporte` (`idreporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Floreria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Floreria`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cliente_idcliente` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  `direccionEntrega` VARCHAR(45) NULL COMMENT '',
  `fechaEntrega` DATE NULL COMMENT '',
  `reporte_idreporte` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idpedido`)  COMMENT '',
  INDEX `fk_pedido_cliente_idx` (`cliente_idcliente` ASC)  COMMENT '',
  INDEX `fk_pedido_reporte1_idx` (`reporte_idreporte` ASC)  COMMENT '',
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `Floreria`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_reporte1`
    FOREIGN KEY (`reporte_idreporte`)
    REFERENCES `Floreria`.`reporte` (`idreporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Floreria`.`flores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Floreria`.`flores` (
  `nombreProducto` VARCHAR(20) NOT NULL COMMENT '',
  `precioCompra` DECIMAL NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `porvedor` VARCHAR(45) NOT NULL COMMENT '',
  `fechaCompra` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`nombreProducto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Floreria`.`accesorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Floreria`.`accesorio` (
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `precio` DECIMAL NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `tamaño` VARCHAR(45) NOT NULL COMMENT '',
  `color` VARCHAR(45) NOT NULL COMMENT '',
  `accesoriocol` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`nombre`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Floreria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Floreria`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombresEmpleado` VARCHAR(45) NOT NULL COMMENT '',
  `apellidosEmpleado` VARCHAR(45) NOT NULL COMMENT '',
  `puesto` VARCHAR(45) NOT NULL COMMENT '',
  `fechaNacimiento` VARCHAR(45) NOT NULL COMMENT '',
  `telefonoCelular` VARCHAR(45) NOT NULL COMMENT '',
  `telefonoCasa` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `pedido_idpedido` INT NOT NULL COMMENT '',
  `accesorio_idaccesorio` INT NOT NULL COMMENT '',
  `flores_idproducto` INT NOT NULL COMMENT '',
  `reporte_idreporte` INT NOT NULL COMMENT '',
  `accesorio_nombreAccesorio` VARCHAR(45) NOT NULL COMMENT '',
  `flores_nombreProducto` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idempleado`)  COMMENT '',
  INDEX `fk_empleado_pedido1_idx` (`pedido_idpedido` ASC)  COMMENT '',
  INDEX `fk_empleado_reporte1_idx` (`reporte_idreporte` ASC)  COMMENT '',
  INDEX `fk_empleado_accesorio1_idx` (`accesorio_nombreAccesorio` ASC)  COMMENT '',
  INDEX `fk_empleado_flores1_idx` (`flores_nombreProducto` ASC)  COMMENT '',
  CONSTRAINT `fk_empleado_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `Floreria`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_reporte1`
    FOREIGN KEY (`reporte_idreporte`)
    REFERENCES `Floreria`.`reporte` (`idreporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_accesorio1`
    FOREIGN KEY (`accesorio_nombreAccesorio`)
    REFERENCES `Floreria`.`accesorio` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_flores1`
    FOREIGN KEY (`flores_nombreProducto`)
    REFERENCES `Floreria`.`flores` (`nombreProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Floreria`.`areglo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Floreria`.`areglo` (
  `idarreglo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `imagen` VARCHAR(500) NOT NULL COMMENT '',
  `nombre` VARCHAR(250) NOT NULL COMMENT '',
  `modelo` INT NOT NULL COMMENT '',
  `descripcion` TEXT(1000) NOT NULL COMMENT '',
  `categoria` VARCHAR(25) NOT NULL COMMENT '',
  `precio` FLOAT NOT NULL COMMENT '',
  `pedido_idpedido` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idarreglo`)  COMMENT '',
  INDEX `fk_areglo_pedido1_idx` (`pedido_idpedido` ASC)  COMMENT '',
  CONSTRAINT `fk_areglo_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `Floreria`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
